#!/usr/bin/env python3
from pathlib import Path
from sys import argv
from typing import Literal

import os
import subprocess
import vdf

WDA_PATHS = [
    Path.home() / '.local' / 'lib' / 'wine',
    Path('/opt/WineDirectALSA')
]


class LibraryFolder:
    root: Path
    appids: list[int]

    def __init__(self, root: Path, appids: list[int]):
        self.root = root
        self.appids = appids


class SteamApp:
    name: str
    appid: int

    def __init__(self, name: str, appid: int):
        self.name = name
        self.appid = appid


class SteamInstallation:
    root: Path
    libraries: list[LibraryFolder]
    apps: list[SteamApp]

    def __init__(self, root: Path):
        if not root.is_dir():
            raise Exception("root is not valid.")

        self.root = root
        self.libraries = []

        for libraryfolder in vdf.load((self.root / "config" / "libraryfolders.vdf").open())['libraryfolders'].values():
            appids = []

            for appid in libraryfolder['apps']:
                appids.append(int(appid))

            self.libraries.append(LibraryFolder(Path(libraryfolder['path']), appids))

        self.apps = []

        for library in self.libraries:
            for appid in library.appids:
                compatdata_path = Path(library.root) / 'steamapps' / 'compatdata' / str(appid)

                if (compatdata_path / 'pfx').is_dir():
                    acf_path = library.root / 'steamapps' / ('appmanifest_' + str(appid) + '.acf')

                    if acf_path.is_file():
                        acf = vdf.load(acf_path.open())

                        self.apps.append(SteamApp(acf['AppState']['name'], appid))

    def get_compatdata(self, appid: int) -> Path:
        for libraryfolder in self.libraries:
            if appid in libraryfolder.appids:
                compatdata_path = Path(libraryfolder.root) / 'steamapps' / 'compatdata' / str(appid)

                if (compatdata_path / 'pfx').is_dir():
                    return compatdata_path

        raise Exception("Proton Prefix not found.")


def get_prefix_proton(compatdata: Path) -> Path:
    config_info = compatdata / 'config_info'

    lines = config_info.read_text().splitlines()
    proton_lib = Path(lines[2])

    # Path recorded from inside a Steam Linux Runtime container.
    if str(proton_lib).startswith('/run/host'):
        proton_lib = Path(
            str(proton_lib).removeprefix('/run/host')
        )

    # .../proton-cachyos-slr/files/lib
    return proton_lib.parent.parent


def choose(prompt: str, count: int) -> int:
    while True:
        try:
            choice = int(input(prompt))

            if 1 <= choice <= count:
                return choice - 1
        except ValueError:
            pass

        print("Invalid choice.")


def to_winepath(path: Path) -> Path:
    strs = str(path).split('/')

    return Path('Z:' + '\\'.join(strs))


def run_umu(wdapath: Path, appid: int, proton: Path, compatdata: Path, commandarg: list[str]) -> int:
    env = os.environ.copy()
    env['WINEPREFIX'] = str(compatdata / 'pfx')
    env['PROTONPATH'] = str(proton)
    env['PROTON_VERB'] = 'runinprefix'
    env['STORE'] = 'steam'
    env['GAMEID'] = str(appid)
    env['WINEDLLPATH'] = str(wdapath)

    arg = commandarg.copy()
    arg.insert(0, 'umu-run')

    result = subprocess.run(arg, env=env)

    return result.returncode


def run_control(wdapath: Path, appid: int, proton: Path, compatdata: Path) -> None:
    commandarg = [str(to_winepath(wdapath / 'x86_64-windows' / 'wdactrl.exe'))]

    run_umu(wdapath, appid, proton, compatdata, commandarg)


def install_to_default_wine_prefix(wdapath: Path) -> None:
    raise Exception("Not Implemented.")


def install_to_steam_proton_wine_prefix(wdapath: Path, appid: int, proton: Path, compatdata: Path) -> None:
    commandarg = ['regsvr32', str(to_winepath(wdapath / 'x86_64-windows' / 'winedirectalsa.dll'))]

    result = run_umu(wdapath, appid, proton, compatdata, commandarg)

    if result == 0:
        run_control(wdapath, appid, proton, compatdata)
        print("Installation Complete!")
    else:
        print(f"Error: returned {result}")


def install_to_non_steam_proton_wine_prefix(wdapath: Path) -> None:
    raise Exception("Not Implemented.")


def get_steam_datas() -> dict[Literal['appid', 'compatdata', 'proton'], int | Path]:
    si = SteamInstallation(Path.home() / ".local" / "share" / "Steam")

    print()

    for i in range(len(si.apps)):
        app = si.apps[i]

        print(f"{i + 1}. {app.name} ({app.appid})")

    print()

    app_choice = choose("Choose an App: ", len(si.apps))
    appid = si.apps[app_choice].appid
    compatdata = si.get_compatdata(appid)
    proton = get_prefix_proton(compatdata)

    return {'appid': appid, 'compatdata': compatdata, 'proton': proton}


def interactive(wdapath: Path) -> None:
    print("Welcome to the WineDirectALSA installer.")
    print()
    #print("1. Install to the Default Wine Prefix")
    print("2. Install to the Steam Proton Wine Prefix")
    #print("3. Install to the non-Steam Proton Wine Prefix")
    print("4. Run control panel only to the Steam Proton Wine Prefix")
    print()

    choice = choose("Choose one: ", 4)

    if choice == 0:
        install_to_default_wine_prefix(wdapath)
    elif choice == 1:
        datas = get_steam_datas()

        install_to_steam_proton_wine_prefix(wdapath, datas['appid'], datas['proton'], datas['compatdata'])
    elif choice == 2:
        install_to_non_steam_proton_wine_prefix(wdapath)
    elif choice == 3:
        datas = get_steam_datas()

        run_control(wdapath, datas['appid'], datas['proton'], datas['compatdata'])


def main():
    for path in WDA_PATHS:
        if path.is_dir():
            args_len = len(argv)

            if args_len == 1:
                interactive(path)

            return

    raise Exception("WineDirectALSA not found!")


if __name__ == "__main__":
    main()
